dist: focal
language: python

python:
    - 3.6
    - 3.7
    - 3.8

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get install -qq python3-numpy python3-scipy 

install:
    - pip install .
    - pip install -r requirements.txt
    - pip install nose-exclude
    - pip install scikit-image

script:
    - python runtests.py --attr='!skip-travis' --cover-package=concert concert
