dist: focal
language: python

python:
    - 3.8

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get install -qq python3-numpy python3-scipy 

install:
    - pip install nose-exclude
    - pip install scikit-image
    - pip install codecov
    - pip install -r requirements.txt
    - pip install .

script:
    - coverage run --source=concert -m nose --attr='!skip-travis'

after_success:
    - codecov
